# Generated by Django 4.1.2 on 2022-11-07 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=63, unique=True)),
                ('password', models.CharField(max_length=127)),
                ('super_admin', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=user.models.User.user_directory_path)),
            ],
            options={
                'verbose_name_plural': 'user',
                'db_table': 'User',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'token',
                'db_table': 'Token',
            },
        ),
    ]
